#!/usr/bin/env ruby
# bls           This is a startup script for use in /etc/init.d 
# chkconfig:    2345 90 20 
# description:  Used to start and stop Adhearsion daemons

APP_NAME = "ahn"
@default_options = [ {
  :name => 'twinners', 
  :app_dir => '/opt/interactivechatsystems/twinners',
  :pid_file => '/var/run/interactivechatsystems/adhearsion.pid' 
} ]
ENV['PATH'] += ':/usr/bin:/opt/interactivechatsystems/adhearsion/bin'

def start_app cmd
  @default_options.each do |project|
    puts "#{cmd.capitalize}ing #{project[:name]}"
    #system("/usr/bin/ruby /opt/interactivechatsystems/adhearsion/bin/ahnctl #{cmd} #{project[:app_dir]} --pid-file=#{project[:pid_file]} &")
    system("/usr/bin/ruby /opt/interactivechatsystems/adhearsion/bin/ahn #{cmd} #{project[:app_dir]} 2>&1 >> /dev/null & echo $! > #{project[:pid_file]} &")
  end
end

case ARGV.first
  #when 'status'
	#TBD
	#puts "Status of #{APP_NAME} is unknown"
  when 'start'
	  start_app 'start'
  when 'stop'
	  start_app 'stop'
  when 'restart'
    start_app 'restart'
end 

unless %w{start stop restart}.include? ARGV.first
  puts "Usage: #{APP_NAME} {start|stop|restart}"
  exit
end