#!/usr/bin/env ruby
# bls           This is a startup script for use in /etc/init.d 
# chkconfig:    2345 80 20 
# description:  Used to start and stop the Twinners BLS Service

APP_NAME = "bls"
@default_options = {
	:app_dir => '/opt/BLS_Java',
	:pid_file => '/var/run/twinners-core_twinners.pid'
}

def start_bls
  puts "Starting #{APP_NAME}"
  system("nohup java -jar #{@default_options[:app_dir]}/twinners-core.jar #{@default_options[:app_dir]}/twinners.conf &")
end

def stop_bls
  pid = File.read(@default_options[:pid_file])
  puts "Stopping #{APP_NAME} with pid #{pid}"
  begin
  	Process.kill(9, pid.to_i)
  rescue => err
	puts err
  end
end

case ARGV.first
  when 'status'
	pid = File.read(@default_options[:pid_file])
	pid_status = system("ps -p #{pid.to_i}")
	if pid_status == TRUE
	  pid_status = "running with pid #{pid}"
    else
      pid_status = "not running"
	end
	puts "Status of #{APP_NAME} is #{pid_status}"
  when 'start'
	start_bls
  when 'stop'
	stop_bls
  when 'restart'
	puts "Re-starting #{APP_NAME}"
	stop_bls
	start_bls
end 

unless %w{start stop restart status}.include? ARGV.first
  puts "Usage: #{APP_NAME} {start|stop|restart}"
  exit
end